#!/usr/bin/env python
# -*- coding: gbk -*-
# File Name: dicConvert.py
# Author: weitao
# mail: weitao@sogou-inc.com
# Created Time: 2016年04月29日 星期五 16时01分08秒
# ToDo: the ratio about sencond find /first file
# For Example:
# Pw @ 2016-04-29 16:01:08
from __future__ import division
import os
import re
import sys


import codecs
import sys

def character_tagging(input_file, output_file):
    input_data = codecs.open(input_file, 'r', 'gbk')
    output_data = codecs.open(output_file, 'r', 'gbk')
    worddic1={}
    for line in input_data.readlines():
        word = line.strip().split("\t")
        worddic1[word[0]]=1
    index=0
    for line in output_data.readlines():
        word = line.strip().split("\t")
        if worddic1.has_key(word[0]):
            index+=1
    nu=len(worddic1)
    ratio=index/nu
    print str(nu)+"\t"+str(ratio)
    input_data.close()
    output_data.close()

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print "Please use: python uni.py input output"
        sys.exit()
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    character_tagging(input_file, output_file)
