#!/usr/bin/env python
# -*- coding: gbk -*-
# File Name: dicConvert.py
# Author: weitao
# mail: weitao@sogou-inc.com
# Created Time: 2016年04月29日 星期五 16时01分08秒
# ToDo:num random interger between low and high
# For Example:
# Pw @ 2016-04-29 16:01:08
import os
import re
import sys
import random


def randnum(low,high,num):
    dataset=[]
    for i in range(0,num):
        dataset.append(random.randint(low,high))
    print dataset


if __name__ == '__main__':
    if len(sys.argv) != 4:
        print "Please use: python rand.py low high num"
        sys.exit()
    low = int(sys.argv[1])
    high = int(sys.argv[2])
    num=int(sys.argv[3])
    randnum(low,high,num)
